### ISSUE TITLE
Nested change in collection is not tracked

### ISSUE THREAD

**Issue by SeasonSeven** [lostmsu/RecursiveChangeNotifier#1]
I add the listener to a viewmodel. The viewmodel has a collection. An item gets added to the collection (till here everything works fine), if this item's property get changed the change is not tracked.

My guess is that the listener subscribes to the collection but doesn't recursive subscribes again to all items being added to this collection?

**Comment by lostmsu** [comment]
@SeasonSeven , please, see the new test in f3e6ab17aa168eeef9855a3e9419442a5e945fd4. It is passing without code changes, so I'd need a more specific description of the scenario you are trying.

Also, ensure, that you are using the latest version. Anything with 0.4+ should be fine.

**Comment by SeasonSeven** [comment]
@lostmsu With 0.4 it works now, thanks for your work!
